#!/bin/sh
cp detail.sh $HOME/Library/Application\ Support/Engine/
cp engine.sh $HOME/Library/Application\ Support/Engine/
cd BIN
cp HandBrakeCLI $HOME/Library/Application\ Support/Engine/
cp mp4art $HOME/Library/Application\ Support/Engine/
cp mp4tags $HOME/Library/Application\ Support/Engine/
cp mp4track $HOME/Library/Application\ Support/Engine/